const categorySource = [
  ["white", "白茶", "清甜柔润 · 久藏生香"],
  ["raw-puer", "普洱生茶", "山野兰香 · 回甘生津"],
  ["ripe-puer", "普洱熟茶", "醇厚温润 · 枣香木香"],
  ["black", "红茶", "蜜甜花香 · 温暖醇柔"],
  ["flower", "花茶", "鲜花窖制 · 香入茶骨"],
  ["green", "绿茶", "鲜爽清雅 · 春日嫩香"],
  ["paste", "茶膏", "一颗一泡 · 随身茶席"],
  ["gift", "礼盒", "多味组合 · 体面茶礼"],
];

export const categories = categorySource.map(([id, name, note], sort) => ({ id, name, note, sort, enabled: true }));

const productSource = [
  ["white-2017-forest", "white", "2017 老树森林古树白茶", "陈香温润，山野甜感", "357g / 饼", 68000, "white-wrapped.png", "老树白茶", "珍藏"],
  ["white-daxueshan-pearls", "white", "大雪山古树白茶龙珠", "一粒一泡，清甜便携", "200g / 罐", 26000, "white-loose.png", "老树白茶", ""],
  ["white-organic-eu", "white", "月上枝欧盟有机白茶", "欧标茶园，毫香清鲜", "50g / 罐", 19800, "white-wrapped.png", "有机白茶", "欧标"],
  ["raw-2023-daxueshan", "raw-puer", "2023 大雪山高杆古树生茶", "高香清劲，甜润耐泡", "200g / 饼", 19800, "raw-cake.png", "古树生茶", "春茶"],
  ["raw-2021-meiziqing", "raw-puer", "2021 梅子箐普洱生茶", "梅香清雅，回甘鲜明", "357g / 饼", 68000, "raw-wrapped.png", "名山茶", ""],
  ["raw-2023-mangfei", "raw-puer", "2023 忙肺正山古树生茶", "香高味厚，山韵清晰", "200g / 饼", 68000, "raw-cake.png", "古树生茶", ""],
  ["ripe-2020-eu", "ripe-puer", "2020 欧标熟茶", "干净甜醇，日常顺饮", "357g / 饼", 29800, "ripe-cake.png", "古树熟茶", "欧标"],
  ["ripe-2012-daxueshan", "ripe-puer", "2012 大雪山熟茶", "陈香沉稳，汤质顺滑", "357g / 饼", 59800, "ripe-cake.png", "古树熟茶", ""],
  ["ripe-heart-tin", "ripe-puer", "欧标小爱心熟茶", "便携小沱，一粒一泡", "100g / 罐", 12800, "ripe-tin.png", "欧标小罐", ""],
  ["black-zhenhanxiang", "black", "枕涵香欧盟有机老树红茶", "蜜香清甜，柔润鲜活", "100g / 罐", 16800, "red-tin.png", "古树烤红", "欧标"],
  ["black-dongfangqi", "black", "东方骑百年古树烤红", "焦糖甜香，醇厚温暖", "100g / 罐", 15800, "red-jar.png", "古树烤红", ""],
  ["black-huangye", "black", "荒野红百年古树晒红", "日晒果香，山野气息", "100g / 罐", 19800, "red-jar.png", "野生晒红", "人气"],
  ["flower-jasmine-hongluo", "flower", "欧标茉莉红螺", "花香清透，甜润耐泡", "100g / 罐", 29800, "jasmine-tin.png", "茉莉花茶", "窖制"],
  ["flower-jasmine-silver", "flower", "欧标茉莉银针", "银针细嫩，香气轻盈", "50g / 罐", 22800, "jasmine-tin.png", "茉莉花茶", ""],
  ["flower-rose-black", "flower", "墨红玫瑰红茶", "玫瑰馥郁，汤感柔和", "100g / 罐", 26000, "rose-jar.png", "桂花玫瑰", ""],
  ["green-shanlan", "green", "山岚欧标黄芽绿茶", "嫩香鲜爽，清甜明亮", "50g / 罐", 16800, "green-tin.png", "高山绿茶", "春茶"],
  ["green-wuliangshan", "green", "无量山春尖", "芽尖细嫩，栗香清鲜", "100g / 罐", 19800, "green-jar.png", "春尖", ""],
  ["green-jingmai", "green", "景迈云雾绿茶", "兰香轻柔，入口鲜甜", "50g / 罐", 18800, "green-tin.png", "高山绿茶", ""],
  ["paste-ripe", "paste", "普洱熟茶膏", "醇厚便携，冷热皆宜", "50g / 袋", 26000, "paste-box.png", "普洱茶膏", "纯茶"],
  ["paste-jasmine", "paste", "茉莉普洱熟茶膏", "茉莉清香，温润顺口", "25g / 袋", 19800, "paste-jar.png", "花香茶膏", ""],
  ["paste-chenpi", "paste", "陈皮普洱熟茶膏", "陈皮清润，熟茶醇甜", "50g / 袋", 26800, "paste-box.png", "普洱茶膏", ""],
  ["gift-jasmine-six", "gift", "6 泡茉莉红礼盒", "轻巧茶礼，六席花香", "6g × 6 / 盒", 18800, "paste-box.png", "九宫格", ""],
  ["gift-white-nine", "gift", "欧标有机白茶九宫格套装", "九种风味，一盒尝鲜", "6g × 9 / 盒", 26600, "gift-nine.png", "九宫格", "茶礼"],
  ["gift-white-twenty", "gift", "欧标有机白茶二十宫格套装", "一盒二十席，分享更从容", "6g × 20 / 盒", 40000, "gift-twenty.png", "二十宫格", ""],
];

export const products = productSource.map(([id, categoryId, name, summary, size, price, image, subcategory, tag], index) => ({
  id,
  sku: `YTEA-${String(index + 1).padStart(4, "0")}`,
  categoryId,
  name,
  summary,
  description: `${summary}。来自予茶精选茶园，支持批次溯源与跨境配送。`,
  size,
  price,
  currency: "CNY",
  image: `/assets/images/products/${image}`,
  images: [`/assets/images/products/${image}`],
  subcategory,
  tag: tag || null,
  stock: 80 + (index % 5) * 30,
  status: "active",
  crossBorder: true,
  traceBatchId: index < 6 ? "YM260318" : "YM260520",
  createdAt: "2026-03-18T08:00:00.000Z",
  updatedAt: "2026-08-24T08:00:00.000Z",
}));

export const seedData = {
  meta: { schemaVersion: 1, createdAt: "2026-08-24T08:00:00.000Z" },
  users: [],
  sessions: [],
  refreshTokens: [],
  memberships: [],
  pointsLedger: [],
  userCoupons: [],
  carts: [],
  addresses: [],
  orders: [],
  payments: [],
  groups: [],
  reservations: [],
  communityMembers: [],
  favorites: [],
  reviews: [],
  notifications: [],
  categories,
  products,
  coupons: [
    { id: "coupon-new-30", name: "新人茶礼", type: "fixed", discount: 3000, minimumSpend: 19900, scope: "all", claimable: true, memberOnly: false, startsAt: "2026-01-01T00:00:00.000Z", endsAt: "2027-01-01T00:00:00.000Z" },
    { id: "coupon-member-50", name: "山席会员专享券", type: "fixed", discount: 5000, minimumSpend: 39900, scope: "all", claimable: true, memberOnly: true, startsAt: "2026-01-01T00:00:00.000Z", endsAt: "2027-01-01T00:00:00.000Z" },
  ],
  promotions: [
    { id: "promo-group-white", kind: "group_buy", name: "山野白茶三人成团", productId: "white-2017-forest", promotionalPrice: 47600, requiredPeople: 3, stock: 30, startsAt: "2026-08-01T00:00:00.000Z", endsAt: "2026-12-31T15:59:59.000Z", status: "active" },
    { id: "promo-flash-green", kind: "flash_sale", name: "今日秒杀·山岚绿茶", productId: "green-shanlan", promotionalPrice: 12800, perUserLimit: 1, stock: 20, startsAt: "2026-08-24T12:00:00.000Z", endsAt: "2026-12-31T13:00:00.000Z", status: "active" },
  ],
  content: [
    { id: "article-origin-jingmai", type: "brand_story", title: "古茶林共生的秘密", summary: "从景迈山的森林生态读懂一片叶子。", body: "景迈山古茶林保留了林茶共生的种植智慧。", image: "/assets/images/tea-origin-culture.png", publishedAt: "2026-08-18T08:00:00.000Z", status: "published" },
    { id: "article-tea-sleep", type: "education", title: "本周慢读：茶与睡眠", summary: "8 分钟了解茶多酚、咖啡因与饮茶时间。", body: "每个人对咖啡因的代谢速度不同，建议根据自身反应调整饮茶时间。", image: "/assets/images/tea-product-stilllife.png", publishedAt: "2026-08-22T08:00:00.000Z", status: "published" },
  ],
  traceBatches: [
    { id: "YM260318", origin: "云南·景迈山", altitude: "1,680m", harvestDate: "2026-03-18", producer: "景迈山予茶合作社", process: ["春梢采摘", "日光萎凋", "低温干燥", "人工拣剔"], certificates: ["产地检验报告", "欧盟有机茶园备案"], status: "verified" },
    { id: "YM260520", origin: "云南·临沧", altitude: "1,920m", harvestDate: "2026-05-20", producer: "予茶古树茶制作所", process: ["手工采摘", "控温萎凋", "分批精制"], certificates: ["质量检验报告"], status: "verified" },
  ],
  events: [
    { id: "event-live-jingmai", type: "live", title: "跟着制茶师云游景迈山", summary: "边听山场故事，边选一款懂你的茶。", startsAt: "2026-09-01T12:00:00.000Z", endsAt: "2026-09-01T13:00:00.000Z", capacity: 500, reservedCount: 86, streamStatus: "scheduled", cover: "/assets/images/tea-origin-culture.png" },
    { id: "event-salon-shanghai", type: "offline", title: "予茶·秋日白茶席", summary: "12 人小席，共饮三道不同年份白茶。", startsAt: "2026-09-12T06:00:00.000Z", endsAt: "2026-09-12T08:00:00.000Z", capacity: 12, reservedCount: 4, streamStatus: "not_applicable", cover: "/assets/images/tea-product-stilllife.png" },
  ],
  communities: [
    { id: "community-jingmai", name: "景迈山春茶共学群", summary: "聊山场、冲泡与新茶记录", memberCount: 286, joinMode: "wechat_enterprise", status: "active" },
  ],
  collaborations: [
    { id: "collab-cup", partner: "青岚窑", title: "一只为岩茶而生的杯", type: "tea_ware", status: "active" },
    { id: "collab-snack", partner: "山食记", title: "低糖桂花茶点礼盒", type: "healthy_food", status: "active" },
  ],
  shippingCountries: [
    { code: "CN", name: "中国大陆", baseFee: 1200, per500gFee: 0, customsRequired: false, etaDays: [2, 5] },
    { code: "HK", name: "中国香港", baseFee: 4800, per500gFee: 1800, customsRequired: true, etaDays: [3, 7] },
    { code: "SG", name: "新加坡", baseFee: 8800, per500gFee: 2600, customsRequired: true, etaDays: [5, 10] },
    { code: "GB", name: "英国", baseFee: 13800, per500gFee: 4200, customsRequired: true, etaDays: [7, 15] },
    { code: "US", name: "美国", baseFee: 15800, per500gFee: 4800, customsRequired: true, etaDays: [7, 18] },
  ],
};
